use_node_class_weights: False
multi_gpu: False

scale_factor: 0.5
batch_size: 2

network_config: 
  num_lstm_layers: 3
  latent_size: 512
  dropout: 0.2
  encoder_model: "lstm"
  feature_extractor: "dino"
